/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package es.udc.ws.runfic.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ThriftMaxCapacityException extends TException implements org.apache.thrift.TBase<ThriftMaxCapacityException, ThriftMaxCapacityException._Fields>, java.io.Serializable, Cloneable, Comparable<ThriftMaxCapacityException> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ThriftMaxCapacityException");

  private static final org.apache.thrift.protocol.TField MAX_CAPACITY_FIELD_DESC = new org.apache.thrift.protocol.TField("maxCapacity", org.apache.thrift.protocol.TType.I32, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ThriftMaxCapacityExceptionStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ThriftMaxCapacityExceptionTupleSchemeFactory());
  }

  public int maxCapacity; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MAX_CAPACITY((short)1, "maxCapacity");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MAX_CAPACITY
          return MAX_CAPACITY;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __MAXCAPACITY_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MAX_CAPACITY, new org.apache.thrift.meta_data.FieldMetaData("maxCapacity", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ThriftMaxCapacityException.class, metaDataMap);
  }

  public ThriftMaxCapacityException() {
  }

  public ThriftMaxCapacityException(
    int maxCapacity)
  {
    this();
    this.maxCapacity = maxCapacity;
    setMaxCapacityIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ThriftMaxCapacityException(ThriftMaxCapacityException other) {
    __isset_bitfield = other.__isset_bitfield;
    this.maxCapacity = other.maxCapacity;
  }

  public ThriftMaxCapacityException deepCopy() {
    return new ThriftMaxCapacityException(this);
  }

  @Override
  public void clear() {
    setMaxCapacityIsSet(false);
    this.maxCapacity = 0;
  }

  public int getMaxCapacity() {
    return this.maxCapacity;
  }

  public ThriftMaxCapacityException setMaxCapacity(int maxCapacity) {
    this.maxCapacity = maxCapacity;
    setMaxCapacityIsSet(true);
    return this;
  }

  public void unsetMaxCapacity() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __MAXCAPACITY_ISSET_ID);
  }

  /** Returns true if field maxCapacity is set (has been assigned a value) and false otherwise */
  public boolean isSetMaxCapacity() {
    return EncodingUtils.testBit(__isset_bitfield, __MAXCAPACITY_ISSET_ID);
  }

  public void setMaxCapacityIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __MAXCAPACITY_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case MAX_CAPACITY:
      if (value == null) {
        unsetMaxCapacity();
      } else {
        setMaxCapacity((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case MAX_CAPACITY:
      return Integer.valueOf(getMaxCapacity());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case MAX_CAPACITY:
      return isSetMaxCapacity();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ThriftMaxCapacityException)
      return this.equals((ThriftMaxCapacityException)that);
    return false;
  }

  public boolean equals(ThriftMaxCapacityException that) {
    if (that == null)
      return false;

    boolean this_present_maxCapacity = true;
    boolean that_present_maxCapacity = true;
    if (this_present_maxCapacity || that_present_maxCapacity) {
      if (!(this_present_maxCapacity && that_present_maxCapacity))
        return false;
      if (this.maxCapacity != that.maxCapacity)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(ThriftMaxCapacityException other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetMaxCapacity()).compareTo(other.isSetMaxCapacity());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMaxCapacity()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.maxCapacity, other.maxCapacity);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ThriftMaxCapacityException(");
    boolean first = true;

    sb.append("maxCapacity:");
    sb.append(this.maxCapacity);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ThriftMaxCapacityExceptionStandardSchemeFactory implements SchemeFactory {
    public ThriftMaxCapacityExceptionStandardScheme getScheme() {
      return new ThriftMaxCapacityExceptionStandardScheme();
    }
  }

  private static class ThriftMaxCapacityExceptionStandardScheme extends StandardScheme<ThriftMaxCapacityException> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ThriftMaxCapacityException struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MAX_CAPACITY
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.maxCapacity = iprot.readI32();
              struct.setMaxCapacityIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ThriftMaxCapacityException struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(MAX_CAPACITY_FIELD_DESC);
      oprot.writeI32(struct.maxCapacity);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ThriftMaxCapacityExceptionTupleSchemeFactory implements SchemeFactory {
    public ThriftMaxCapacityExceptionTupleScheme getScheme() {
      return new ThriftMaxCapacityExceptionTupleScheme();
    }
  }

  private static class ThriftMaxCapacityExceptionTupleScheme extends TupleScheme<ThriftMaxCapacityException> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ThriftMaxCapacityException struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetMaxCapacity()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetMaxCapacity()) {
        oprot.writeI32(struct.maxCapacity);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ThriftMaxCapacityException struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.maxCapacity = iprot.readI32();
        struct.setMaxCapacityIsSet(true);
      }
    }
  }

}

