/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package es.udc.ws.runfic.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ThriftAlreadyRegisteredException extends TException implements org.apache.thrift.TBase<ThriftAlreadyRegisteredException, ThriftAlreadyRegisteredException._Fields>, java.io.Serializable, Cloneable, Comparable<ThriftAlreadyRegisteredException> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ThriftAlreadyRegisteredException");

  private static final org.apache.thrift.protocol.TField EMAIL_USUARIO_FIELD_DESC = new org.apache.thrift.protocol.TField("emailUsuario", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ThriftAlreadyRegisteredExceptionStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ThriftAlreadyRegisteredExceptionTupleSchemeFactory());
  }

  public String emailUsuario; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    EMAIL_USUARIO((short)1, "emailUsuario");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // EMAIL_USUARIO
          return EMAIL_USUARIO;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.EMAIL_USUARIO, new org.apache.thrift.meta_data.FieldMetaData("emailUsuario", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ThriftAlreadyRegisteredException.class, metaDataMap);
  }

  public ThriftAlreadyRegisteredException() {
  }

  public ThriftAlreadyRegisteredException(
    String emailUsuario)
  {
    this();
    this.emailUsuario = emailUsuario;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ThriftAlreadyRegisteredException(ThriftAlreadyRegisteredException other) {
    if (other.isSetEmailUsuario()) {
      this.emailUsuario = other.emailUsuario;
    }
  }

  public ThriftAlreadyRegisteredException deepCopy() {
    return new ThriftAlreadyRegisteredException(this);
  }

  @Override
  public void clear() {
    this.emailUsuario = null;
  }

  public String getEmailUsuario() {
    return this.emailUsuario;
  }

  public ThriftAlreadyRegisteredException setEmailUsuario(String emailUsuario) {
    this.emailUsuario = emailUsuario;
    return this;
  }

  public void unsetEmailUsuario() {
    this.emailUsuario = null;
  }

  /** Returns true if field emailUsuario is set (has been assigned a value) and false otherwise */
  public boolean isSetEmailUsuario() {
    return this.emailUsuario != null;
  }

  public void setEmailUsuarioIsSet(boolean value) {
    if (!value) {
      this.emailUsuario = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case EMAIL_USUARIO:
      if (value == null) {
        unsetEmailUsuario();
      } else {
        setEmailUsuario((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case EMAIL_USUARIO:
      return getEmailUsuario();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case EMAIL_USUARIO:
      return isSetEmailUsuario();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ThriftAlreadyRegisteredException)
      return this.equals((ThriftAlreadyRegisteredException)that);
    return false;
  }

  public boolean equals(ThriftAlreadyRegisteredException that) {
    if (that == null)
      return false;

    boolean this_present_emailUsuario = true && this.isSetEmailUsuario();
    boolean that_present_emailUsuario = true && that.isSetEmailUsuario();
    if (this_present_emailUsuario || that_present_emailUsuario) {
      if (!(this_present_emailUsuario && that_present_emailUsuario))
        return false;
      if (!this.emailUsuario.equals(that.emailUsuario))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(ThriftAlreadyRegisteredException other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetEmailUsuario()).compareTo(other.isSetEmailUsuario());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEmailUsuario()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.emailUsuario, other.emailUsuario);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ThriftAlreadyRegisteredException(");
    boolean first = true;

    sb.append("emailUsuario:");
    if (this.emailUsuario == null) {
      sb.append("null");
    } else {
      sb.append(this.emailUsuario);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ThriftAlreadyRegisteredExceptionStandardSchemeFactory implements SchemeFactory {
    public ThriftAlreadyRegisteredExceptionStandardScheme getScheme() {
      return new ThriftAlreadyRegisteredExceptionStandardScheme();
    }
  }

  private static class ThriftAlreadyRegisteredExceptionStandardScheme extends StandardScheme<ThriftAlreadyRegisteredException> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ThriftAlreadyRegisteredException struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // EMAIL_USUARIO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.emailUsuario = iprot.readString();
              struct.setEmailUsuarioIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ThriftAlreadyRegisteredException struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.emailUsuario != null) {
        oprot.writeFieldBegin(EMAIL_USUARIO_FIELD_DESC);
        oprot.writeString(struct.emailUsuario);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ThriftAlreadyRegisteredExceptionTupleSchemeFactory implements SchemeFactory {
    public ThriftAlreadyRegisteredExceptionTupleScheme getScheme() {
      return new ThriftAlreadyRegisteredExceptionTupleScheme();
    }
  }

  private static class ThriftAlreadyRegisteredExceptionTupleScheme extends TupleScheme<ThriftAlreadyRegisteredException> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ThriftAlreadyRegisteredException struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetEmailUsuario()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetEmailUsuario()) {
        oprot.writeString(struct.emailUsuario);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ThriftAlreadyRegisteredException struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.emailUsuario = iprot.readString();
        struct.setEmailUsuarioIsSet(true);
      }
    }
  }

}

